### ISSUE TITLE
Investigate blank api URL when Waltz is first started

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#67] opened 2013-10-30 18:07 UTC

**Comment by landakram** [comment] 2013-10-30 23:00
I'm pretty sure this happened because of the switch from `cydoemus_url` to `cy_url`, and we all upgraded our plugins without deleting them. I haven't been able to reproduce, so I'm closing for now.

**Closed as completed by landakram** 2013-10-30 23:00 UTC
Labels: mvp
